name: Checking 02-intro-javascript
on:
  push:
    branches: [master]
    paths:
    - 02-intro-javascript/**

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: WolfYe98/ReactCursoUdemy
          path: 02-intro-javascript