name: CI 01-Introduccion
on:
  push:
    branches:
    - master
    paths:
    - 01-introduccion/**

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: WolfYe98/ReactCursoUdemy
          path: 01-introduccion